# Generated by Django 5.1.4 on 2024-12-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='host_id',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
